
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Gestion_Contacts", targetNamespace = "http://service.ws.soap_wsServer_Contact/", wsdlLocation = "http://localhost:9999/?wsdl")
public class GestionContacts
    extends Service
{

    private final static URL GESTIONCONTACTS_WSDL_LOCATION;
    private final static WebServiceException GESTIONCONTACTS_EXCEPTION;
    private final static QName GESTIONCONTACTS_QNAME = new QName("http://service.ws.soap_wsServer_Contact/", "Gestion_Contacts");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONCONTACTS_WSDL_LOCATION = url;
        GESTIONCONTACTS_EXCEPTION = e;
    }

    public GestionContacts() {
        super(__getWsdlLocation(), GESTIONCONTACTS_QNAME);
    }

    public GestionContacts(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONCONTACTS_QNAME, features);
    }

    public GestionContacts(URL wsdlLocation) {
        super(wsdlLocation, GESTIONCONTACTS_QNAME);
    }

    public GestionContacts(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONCONTACTS_QNAME, features);
    }

    public GestionContacts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionContacts(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactServicePort")
    public ContactService getContactServicePort() {
        return super.getPort(new QName("http://service.ws.soap_wsServer_Contact/", "ContactServicePort"), ContactService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactServicePort")
    public ContactService getContactServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.soap_wsServer_Contact/", "ContactServicePort"), ContactService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONCONTACTS_EXCEPTION!= null) {
            throw GESTIONCONTACTS_EXCEPTION;
        }
        return GESTIONCONTACTS_WSDL_LOCATION;
    }

}
